### ISSUE TITLE
Change titles at top of poster

### ISSUE THREAD

**Issue by jmckenna** [pgRouting/osgeo#11]
Readers will not know what the GSoC logo is, by itself.  Therefore I propose to change the title at the top of the poster to:

- change 1st line of title to: "Success with [logo] OSGeo"
- change 2nd line of title to: "+ [logo] Google Summer of Code"
- change 3rd line of title (notice the capitals) to : "Become an Open Source Developer"

**Comment by cvvergara** [comment]
Maddie suggested:
you might use a logo that has the writing in it, like https://lh5.googleusercontent.com/_uwWzNbZjbpgSICWTqjo2Yn-b3lzj2y-Um8XbhXyhRAMecshGI0PnGK6N0fU2IDFTFvdg7d3kbKq-5CQKYgtpavztSCeC33QGvs2-AHM0csx5kc-RwleCIHysG47FfrH6uvDl82Z
or https://blog.ninux.org/wp-content/uploads/2017/03/GSoC2016Logo.jpg

**Comment by jmckenna** [comment]
looks good!  (https://github.com/pgRouting/osgeo/blob/gsoc-poster/GSoc-poster/poster-test5.pdf)
