### ISSUE TITLE
More comments from Jeff

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/osgeo#14]
Thank you for all of this effort.  Some more comments:

- [x] in the "OSGeo Projects" section, add a missing type: "Content Management Systems"
- [x] in the "Weekly Report" section, remove the extra space before the "!"
- [x] in the "Be patient" section, change to "Be Patient" (capitalized), and also remove an extra space between "make  the"
- [x] in the section "Application Review", change to lowercase "first"
- [x] in the section "OSGeo Live", change to "Get to know the projects"

Thanks,
-jeff

**Comment by hellik** [comment]
Some more comments:

- "What is your interest?." -> drop the point after question mark

- in the section _Be proactive_: some items have a point at the end of the sentence, some not; should be uniform

- the same is in the section _Proposal_: some of the items have a ending point, some not

- the same is in the section _Bonding_: some of the items have a ending point, some not

**Comment by cvvergara** [comment]
@jmckenna 

"Content Management Systems" is too large to be on one row of the list, can I use "CMS"???

**Comment by jmckenna** [comment]
Yes to using "CMS" instead

**Comment by cvvergara** [comment]
@hellik @jmckenna
I made the changes for this issue.
Can you check that they are correct.
https://github.com/pgRouting/osgeo/blob/gsoc-poster/GSoc-poster/poster-test5.pdf
So that I can close.

**Comment by jmckenna** [comment]
this issue remains:  in the "Be patient" section, remove an extra space between "make  the"

**Comment by jmckenna** [comment]
or is it my eyes that think there is an extra space there??

**Comment by cvvergara** [comment]
No, its my eyes, I lost my eyeglasses and I am using old ones.

**Comment by cvvergara** [comment]
@jmckenna 
I will close, please reopen if something is wrong

**Comment by jmckenna** [comment]
verified
