### ISSUE TITLE
"Contact Project" text

### ISSUE THREAD

**Issue by mentaer** [pgRouting/osgeo#15]
I would suggest changing from "Projects don’t look for you, you look for them!" to 
"Projects don’t know you yet, so contact them!"
except I misunderstood what this item is about, but I guess its about "first contact"? Or is it about the contact during GSoC?

**Comment by cvvergara** [comment]
@mentaer 
It's  about the first contact.

**Comment by cvvergara** [comment]
fixed and pushed
you can refresh

**Comment by cvvergara** [comment]
@mentaer 
Please, can you review and close issues that I have fixed

**Comment by cvvergara** [comment]
@mentaer 
I will close, please reopen if something is wrong
