### ISSUE TITLE
text of "Know the Project"

### ISSUE THREAD

**Issue by mentaer** [pgRouting/osgeo#16]
suggest change to "Projects have webpages, documention and mail lists!"

**Comment by cvvergara** [comment]
Done, pushed changes of three issues #16 #18 and #19 

@mentaer @jmckenna
Please refresh https://github.com/pgRouting/osgeo/blob/gsoc-poster/GSoc-poster/poster-test5.pdf
please verify and close what needs to be closed

**Comment by cvvergara** [comment]
@mentaer 
I will close, please reopen if something is wrong
