### ISSUE TITLE
"Infrastructure" text

### ISSUE THREAD

**Issue by mentaer** [pgRouting/osgeo#18]
Not sure what is meant with "Get ready to start coding!" - perhaps change to "Be ready to start coding at home"?

**Comment by cvvergara** [comment]
@jmckenna
What about:
Install what you need for coding!

**Comment by mentaer** [comment]
yes - that sounds even better :)

**Comment by cvvergara** [comment]
Done ...
pending push

**Comment by jmckenna** [comment]
I also like "Install what you need for coding!"

**Comment by cvvergara** [comment]
@mentaer 
I will close, please reopen if something is wrong
