### ISSUE TITLE
QGIS logo changed

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/osgeo#2]
replace QGIS logo with the new logo - https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKAF_dmoOusK5Wed_iScTU3R5wiutQiQ_fBDeA4f5QC1IQ75jc7Q

**Comment by jmckenna** [comment]
thanks for changing the QGIS logo (I see it now in the poster preview: https://github.com/pgRouting/osgeo/blob/gsoc-poster/GSoc-poster/poster-test5.pdf).  Verified.

**Comment by cvvergara** [comment]
Thanks
