### ISSUE TITLE
"Be Proactive" text suggestions

### ISSUE THREAD

**Issue by mentaer** [pgRouting/osgeo#20]
OSGeo Projects:
- What will convert you from novice to authority? => What will convert you from novice to expert?
- Not sure what is meant with "What will make you feel like a hobby?" => could it be "What will make you feel coding as your hobby?"
Contribute:
- "Practice contributing code fixes." => "Practice by contributing bug fixes".
- "Practice contributing documentation fixes." => Practice by contributing documentation".

**Comment by jmckenna** [comment]
Interesting, I had never noticed the lower section of the poster :)

Feedback on "Be Proactive" section:

OSGeo Projects:

- agree with change from @mentaer for novice/expert
- "What will make you feel like a hobby?" => "What will you enjoy working on?"

OSGeo Live:

- the entire poster must reference it correctly as "OSGeo-Live" not "OSGeo Live"
- "Familizarize with the projects." => "Become familiar with the projects."

Make a Calendar:

- "Add your region Holyday dates" => "Include your region's holidays."

Know the Project:

- "Read user's documentation." =>  "Read the user documentation."
- "Read developer's documentation." =>   "Read the developer documentation."
- "Read wiki." => "Read the project wiki."
- "Read issues." =>  "Read the bug tracker issues."

Contribute:

- "Different repository platforms." => "Learn different repository platforms (GitHub, SVN, Gogs)."

**Comment by cvvergara** [comment]
Done

**Comment by jmckenna** [comment]
Verified
