### ISSUE TITLE
proposal + bonding + coding text

### ISSUE THREAD

**Issue by mentaer** [pgRouting/osgeo#21]
proposal text: 
- suggest change from "Have complete proposal." => "Have a complete proposal" => or: "Strive for a complete proposal"
bonding text:
- "Participate on project meetings." => "Participate in project meetings."
coding text:
- I guess in the "follow standards" part all "on" need to be change to "in" ; but I am also not an english native speaker. :(

**Comment by jmckenna** [comment]
Proposal:

- "Aplication Review" => "Application Review"
- agree with @mentaer , probably "Aim for a complete proposal."
- agree with @mentaer for project meetings change

Bonding:

- "Due dates adjusted to your time zone." => "Adjust due dates to your time zone."
- "Pseudo code your project." => "First write your code in pseudocode."
- "Participate on project meetings." => "Participate in project meetings."

Coding

- "Uniformity on..." is very wordy.  I suggest using something easier to read as:

  Uniform engineering. 
  Uniform technical criteria. 
  Uniform methods. 
  Uniform processes. 
  Uniform practices.

**Comment by cvvergara** [comment]
Done

**Comment by jmckenna** [comment]
Verified
