### ISSUE TITLE
suggestion for title:

### ISSUE THREAD

**Issue by mentaer** [pgRouting/osgeo#22]
How about changing from "Success with" to "Your Success with"?

**Comment by cvvergara** [comment]
Well, its everyone's success ..
- its the students personal success
- its the projects sucess when there s a code contribution
- its OSGeo success when more people care about OSGeo projects growth
- its GSoC program success to have a new student involved on open source

**Comment by jmckenna** [comment]
Hmm.   If we were to change "Success with" at all, I would change to "Grow with"

It opens a can of worms though, as we might not be able to agree on a change.   If so, I'm fine with it as "Success with".

**Comment by cvvergara** [comment]
Keeping as it is then
