### ISSUE TITLE
font size

### ISSUE THREAD

**Issue by mentaer** [pgRouting/osgeo#24]
Hi, I wonder what the font size is - I can`t print A0 :(
So in general for the text at the bottom you should strive to have at least like size 14pt for a poster, perhaps. But you know if its is readable when you print it and stand 2 meters away from the poster.
For figures in publications/magazines the minimum-minimum size I use is 8pt.

**Comment by cvvergara** [comment]
Font sizes are 13.94 (wierd number, maybe it change because I had to resize everything because the title got bigger)

**Comment by mentaer** [comment]
cool, that should work then :)
