### ISSUE TITLE
Mapbender Logo

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/osgeo#3]
@astroidex
 replace Mapbender logo - I will send you a good logo in the next days logo and text with no background

**Comment by astroidex** [comment]
Hi vicky - sorry for the delay. descission on the logo will be on tuesday. hope that is still in time

**Comment by cvvergara** [comment]
@astroidex Sure it is time.

**Comment by astroidex** [comment]
Hello Vicky. Here comes the new logo without a border. We name it now Mapbender instead of Mapbender3

![mapbender](https://user-images.githubusercontent.com/996298/30524970-fb1f8e9c-9bfd-11e7-8a5b-571f6793015b.png)

**Comment by cvvergara** [comment]
For the poster right?

**Comment by astroidex** [comment]
yes

**Comment by cvvergara** [comment]
Please check:
https://github.com/pgRouting/osgeo/blob/gsoc-poster/GSoc-poster/poster-test5.pdf
and the name of the file is Mapbender3, I didnt change it to have it without the 3, because Its a linked image in the svg.
https://github.com/pgRouting/osgeo/blob/gsoc-poster/GSoc-poster/logos/Mapbender3.png

**Comment by cvvergara** [comment]
@astroidex 
cant you check and so that I can close

**Comment by astroidex** [comment]
sorry. I missed to give feedback. Looks good.
