### ISSUE TITLE
Only OSGeo related projects

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/osgeo#5]
- [x] Remove from repository
- [x] Remove from poster logos that are not:
  - OSGeo projects
  - OSGeo Incubation
  - OSGeo Community
  - OSGeo Guest (maybe a non OSGeo related project under the umbrella of a past year GSoC program)

**Comment by cvvergara** [comment]
- [ ]    AtlasStyler.png
- [ ]      geomoose.png
- [ ]          GMT.png
- [ ]                           ipython.png
- [ ]          Kosmo.png
- [ ]           MapServer.png
- [ ]                     naturalearth.png
- [ ]         opencpn.svg
- [ ]         pgRouting.png  QGIS.jpg
- [ ]             TileCache.svg   zygrib.png
- [ ]    cartaro.png
- [ ]          GeoNetwork.png
- [ ]        gpsdrive.png
- [ ]                      iris.png
- [ ]             leaflet.png
- [ ]         mapslicer.png
- [ ]                     naturalearth.svg
- [ ]         openjump.png
- [ ]        pgrouting.svg
- [ ]      rasdaman.png
- [ ]         tilemill.png
- [ ]    cesium.png
- [ ]           geonode.png
- [ ]           gpsprune.png
- [ ]                      istsos.png
- [ ]           libLAS.png
- [ ]          MapWindow.png
- [ ]                     ncdataset.png
- [ ]            OpenLayers.png
- [ ]      PostGIS.png
- [ ]        README.md
- [ ]            tilesync.png
- [ ]    deegree.png
- [ ]          Geopublisher.png
- [ ]      grassgis_logo_multilayer.svg
- [ ]      josm.png
- [ ]             Mapbender3.png
- [ ]      marble.png
- [ ]                        ncWMS.png
- [ ]                OpenLayers.svg
- [ ]      proj4.png
- [ ]          R.png
- [ ]                TinyOWS.png
- [ ]    eoxserver.png
- [ ]        GeoServer.png
- [ ]         gvSIG.png
- [ ]                         jts_project.png
- [ ]      mapfish.png
- [ ]         mb-system.png
- [ ]                     netcdf.png
- [ ]               osgearth.png
- [ ]        prune.png
- [ ]          saga.png
- [ ]             uDig.png
- [ ]    GDAL.png
- [ ]             GEOS.png
- [ ]              ideditor.png
- [ ]                      JUMP.png
- [ ]             MapGuideOS.png
- [ ]      metacrs.png
- [ ]                       OGC-left.png
- [ ]             osm.png
- [ ]             psma.png
- [ ]           sahana-eden.png
- [ ]      ushahidi.png
- [ ]    geokettle.png
- [ ]    GeoTools.png
- [ ]          ideditor.svg
- [ ]                      jupyter.png
- [ ]          mapnik.png
- [ ]          NasaWorldWind-horizontal.png
- [ ]      OneBusAway_Logo.svg 
- [ ]     ossim.png
- [ ]           pycsw.png
- [ ]          spatialite.png
- [ ]       viking.png
- [ ]    geomajas.png
- [ ]         geowebcache.png
- [ ]       ipnb.png
- [ ]                          jupyter.svg
- [ ]          mapproxy.png
- [ ]        NasaWorldWind-vertical.png
- [ ]        opencpn.png
- [ ]              otb.png
- [ ]             pywps.png
- [ ]          TileCache.png
- [ ]        zoo-simple.png

**Comment by cvvergara** [comment]
@jmckenna 
If this is ok now tell me so I can close

**Comment by jmckenna** [comment]
Verified, this poster version looks great!
