### ISSUE TITLE
change text inside the "Follow Standards" section

### ISSUE THREAD

**Issue by jmckenna** [pgRouting/osgeo#9]
Change the text "Make the code easy to read!" to "Make the code easy to deploy!"

**Comment by cvvergara** [comment]
@jmckenna 
Fixed issues 6 7 8 9
https://github.com/pgRouting/osgeo/blob/gsoc-poster/GSoc-poster/poster-test5.pdf

Please verify and close if done properly

**Comment by jmckenna** [comment]
verified, thanks!
